stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification:
  recipients:
  - recipient: https://oapi.dingtalk.com/robot/send?access_token=55294e2c78c147bb1a845c1fae261d505ab9849f94b6fd62a1109273e6ded
    notifier: c-lf6t6:n-vtsp6
  condition:
  - Success
  - Changed
  - Failed
